Update image_compressor.py
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS' has been solved by replacing ANTIALIAS which is deprecated through many previous versions with PIL.Image.LANCZOS